// <auto-generated />
using System;
using DataAccessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Entities.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RequestedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("RequestType", "TargetId", "Status");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("BusinessObjects.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("None");

                    b.Property<string>("TagNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique()
                        .HasFilter("[IdentityNumber] IS NOT NULL");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("BusinessObjects.Entities.GuestAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleSubjectId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique()
                        .HasFilter("[GoogleSubjectId] IS NOT NULL");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.ToTable("GuestAccounts");
                });

            modelBuilder.Entity("BusinessObjects.Entities.HousekeepingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HandledByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Other");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HandledByUserId");

                    b.HasIndex("StayId");

                    b.HasIndex("Status", "RequestedAt");

                    b.ToTable("HousekeepingRequests");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("RoomCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StayId")
                        .HasColumnType("int");

                    b.Property<decimal>("SurchargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StayId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReceivedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ReceivedByUserId");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount_Positive", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xem nhân viên",
                            DisplayName = "Xem nhân viên",
                            IsActive = true,
                            Module = "Người dùng",
                            PermissionCode = "user.view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quản lý nhân viên",
                            DisplayName = "Quản lý nhân viên",
                            IsActive = true,
                            Module = "Người dùng",
                            PermissionCode = "user.manage"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cấu hình phân quyền",
                            DisplayName = "Cấu hình phân quyền",
                            IsActive = true,
                            Module = "Phân quyền",
                            PermissionCode = "permission.manage"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xem nhật ký hệ thống",
                            DisplayName = "Xem nhật ký hệ thống",
                            IsActive = true,
                            Module = "Nhật ký",
                            PermissionCode = "audit.view"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Xem phòng",
                            DisplayName = "Xem phòng",
                            IsActive = true,
                            Module = "Phòng",
                            PermissionCode = "room.view"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Quản lý phòng",
                            DisplayName = "Quản lý phòng",
                            IsActive = true,
                            Module = "Phòng",
                            PermissionCode = "room.manage"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Yêu cầu bảo trì phòng",
                            DisplayName = "Yêu cầu bảo trì phòng",
                            IsActive = true,
                            Module = "Phòng",
                            PermissionCode = "room.maintenance.request"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Duyệt bảo trì phòng",
                            DisplayName = "Duyệt bảo trì phòng",
                            IsActive = true,
                            Module = "Phòng",
                            PermissionCode = "room.maintenance.approve"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Xem đặt phòng",
                            DisplayName = "Xem đặt phòng",
                            IsActive = true,
                            Module = "Đặt phòng",
                            PermissionCode = "reservation.view"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tạo đặt phòng",
                            DisplayName = "Tạo đặt phòng",
                            IsActive = true,
                            Module = "Đặt phòng",
                            PermissionCode = "reservation.create"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Cập nhật đặt phòng",
                            DisplayName = "Cập nhật đặt phòng",
                            IsActive = true,
                            Module = "Đặt phòng",
                            PermissionCode = "reservation.update"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Yêu cầu hủy đặt phòng",
                            DisplayName = "Yêu cầu hủy đặt phòng",
                            IsActive = true,
                            Module = "Đặt phòng",
                            PermissionCode = "reservation.cancel.request"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Duyệt hủy đặt phòng",
                            DisplayName = "Duyệt hủy đặt phòng",
                            IsActive = true,
                            Module = "Đặt phòng",
                            PermissionCode = "reservation.cancel.approve"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Nhận phòng",
                            DisplayName = "Nhận phòng",
                            IsActive = true,
                            Module = "Lượt ở",
                            PermissionCode = "stay.check_in"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Gia hạn lượt ở",
                            DisplayName = "Gia hạn lượt ở",
                            IsActive = true,
                            Module = "Lượt ở",
                            PermissionCode = "stay.extend"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Trả phòng",
                            DisplayName = "Trả phòng",
                            IsActive = true,
                            Module = "Lượt ở",
                            PermissionCode = "stay.check_out"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Xem khách hàng",
                            DisplayName = "Xem khách hàng",
                            IsActive = true,
                            Module = "Khách hàng",
                            PermissionCode = "guest.view"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Quản lý khách hàng",
                            DisplayName = "Quản lý khách hàng",
                            IsActive = true,
                            Module = "Khách hàng",
                            PermissionCode = "guest.manage"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Quản lý danh mục dịch vụ",
                            DisplayName = "Quản lý danh mục dịch vụ",
                            IsActive = true,
                            Module = "Dịch vụ",
                            PermissionCode = "service.catalog.manage"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Tạo đơn dịch vụ",
                            DisplayName = "Tạo đơn dịch vụ",
                            IsActive = true,
                            Module = "Dịch vụ",
                            PermissionCode = "service.order.create"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Xử lý đơn dịch vụ",
                            DisplayName = "Xử lý đơn dịch vụ",
                            IsActive = true,
                            Module = "Dịch vụ",
                            PermissionCode = "service.order.process"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Quản lý danh mục phụ thu",
                            DisplayName = "Quản lý danh mục phụ thu",
                            IsActive = true,
                            Module = "Phụ thu",
                            PermissionCode = "surcharge.catalog.manage"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Thêm phụ thu",
                            DisplayName = "Thêm phụ thu",
                            IsActive = true,
                            Module = "Phụ thu",
                            PermissionCode = "surcharge.add"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Quản lý khuyến mãi",
                            DisplayName = "Quản lý khuyến mãi",
                            IsActive = true,
                            Module = "Khuyến mãi",
                            PermissionCode = "promotion.manage"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Xem hóa đơn",
                            DisplayName = "Xem hóa đơn",
                            IsActive = true,
                            Module = "Hóa đơn",
                            PermissionCode = "invoice.view"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Lập và tính lại hóa đơn",
                            DisplayName = "Lập và tính lại hóa đơn",
                            IsActive = true,
                            Module = "Hóa đơn",
                            PermissionCode = "invoice.prepare"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Yêu cầu giảm giá",
                            DisplayName = "Yêu cầu giảm giá",
                            IsActive = true,
                            Module = "Hóa đơn",
                            PermissionCode = "invoice.discount.request"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Duyệt giảm giá",
                            DisplayName = "Duyệt giảm giá",
                            IsActive = true,
                            Module = "Hóa đơn",
                            PermissionCode = "invoice.discount.approve"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Yêu cầu hủy hóa đơn",
                            DisplayName = "Yêu cầu hủy hóa đơn",
                            IsActive = true,
                            Module = "Hóa đơn",
                            PermissionCode = "invoice.cancel.request"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Duyệt hủy hóa đơn",
                            DisplayName = "Duyệt hủy hóa đơn",
                            IsActive = true,
                            Module = "Hóa đơn",
                            PermissionCode = "invoice.cancel.approve"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Ghi nhận thanh toán",
                            DisplayName = "Ghi nhận thanh toán",
                            IsActive = true,
                            Module = "Thanh toán",
                            PermissionCode = "payment.record"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Yêu cầu hủy giao dịch",
                            DisplayName = "Yêu cầu hủy giao dịch",
                            IsActive = true,
                            Module = "Thanh toán",
                            PermissionCode = "payment.void.request"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Duyệt hủy giao dịch",
                            DisplayName = "Duyệt hủy giao dịch",
                            IsActive = true,
                            Module = "Thanh toán",
                            PermissionCode = "payment.void.approve"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Xem báo cáo",
                            DisplayName = "Xem báo cáo",
                            IsActive = true,
                            Module = "Báo cáo",
                            PermissionCode = "report.view"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Xuất báo cáo",
                            DisplayName = "Xuất báo cáo",
                            IsActive = true,
                            Module = "Báo cáo",
                            PermissionCode = "report.export"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DepositPaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepositPaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations", t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_CheckOutDate_CheckInDate", "[CheckOutDate] > [CheckInDate]");

                            t.HasCheckConstraint("CK_Reservation_DepositAmount_NonNegative", "[DepositAmount] IS NULL OR [DepositAmount] >= 0");

                            t.HasCheckConstraint("CK_Reservation_NumberOfGuests_MinValue", "[NumberOfGuests] >= 1");
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản lý tài khoản, quyền và an toàn hệ thống",
                            DisplayName = "Quản trị viên",
                            IsActive = true,
                            IsSystemRole = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quản lý vận hành, báo cáo và phê duyệt",
                            DisplayName = "Quản lý",
                            IsActive = true,
                            IsSystemRole = true,
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thực hiện nghiệp vụ tại quầy",
                            DisplayName = "Lễ tân",
                            IsActive = true,
                            IsSystemRole = true,
                            RoleName = "Receptionist"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thực hiện dịch vụ và yêu cầu buồng phòng",
                            DisplayName = "Nhân viên dịch vụ",
                            IsActive = true,
                            IsSystemRole = true,
                            RoleName = "ServiceStaff"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 33,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 34,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 35,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 12,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 14,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 27,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 29,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 31,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 32,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 7,
                            IsAllowed = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 21,
                            IsAllowed = true
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = 1,
                            IsActive = true,
                            RoomNumber = "101",
                            RoomTypeId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Floor = 1,
                            IsActive = true,
                            RoomNumber = "102",
                            RoomTypeId = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Floor = 2,
                            IsActive = true,
                            RoomNumber = "201",
                            RoomTypeId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Floor = 2,
                            IsActive = true,
                            RoomNumber = "202",
                            RoomTypeId = 2,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Floor = 3,
                            IsActive = true,
                            RoomNumber = "301",
                            RoomTypeId = 3,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 6,
                            Floor = 4,
                            IsActive = true,
                            RoomNumber = "401",
                            RoomTypeId = 4,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 500000.00m,
                            Capacity = 2,
                            Description = "Standard Room with basic amenities",
                            IsActive = true,
                            TypeName = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 800000.00m,
                            Capacity = 2,
                            Description = "Deluxe Room with premium comfort",
                            IsActive = true,
                            TypeName = "Deluxe"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 1200000.00m,
                            Capacity = 4,
                            Description = "Luxurious Suite with separate living area",
                            IsActive = true,
                            TypeName = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 1500000.00m,
                            Capacity = 6,
                            Description = "Spacious Room ideal for families",
                            IsActive = true,
                            TypeName = "Family Room"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Restaurant",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Laundry",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ServiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            ServiceCategoryId = 1,
                            ServiceName = "Breakfast Set",
                            UnitPrice = 80000.00m
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            ServiceCategoryId = 1,
                            ServiceName = "Dinner Set",
                            UnitPrice = 150000.00m
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            ServiceCategoryId = 1,
                            ServiceName = "Bottled Water",
                            UnitPrice = 15000.00m
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            ServiceCategoryId = 2,
                            ServiceName = "Shirt Washing",
                            UnitPrice = 20000.00m
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = true,
                            ServiceCategoryId = 2,
                            ServiceName = "Pants Washing",
                            UnitPrice = 25000.00m
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            ServiceCategoryId = 2,
                            ServiceName = "Ironing Service",
                            UnitPrice = 15000.00m
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StayId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StayId");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("ServiceOrderDetails");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Stay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckedInByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CheckedOutByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CheckedInByUserId");

                    b.HasIndex("CheckedOutByUserId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Stays");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Surcharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StayId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SurchargeItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StayId");

                    b.HasIndex("SurchargeItemId");

                    b.ToTable("Surcharges");
                });

            modelBuilder.Entity("BusinessObjects.Entities.SurchargeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SurchargeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Khăn tắm",
                            Unit = "cái",
                            UnitPrice = 80000m
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Khăn mặt",
                            Unit = "cái",
                            UnitPrice = 30000m
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Dép đi trong phòng",
                            Unit = "đôi",
                            UnitPrice = 40000m
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Remote TV",
                            Unit = "cái",
                            UnitPrice = 200000m
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Thẻ từ / chìa khóa phòng",
                            Unit = "cái",
                            UnitPrice = 100000m
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Ấm siêu tốc",
                            Unit = "cái",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Ly / cốc thủy tinh",
                            Unit = "cái",
                            UnitPrice = 30000m
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Chăn / ga (ố bẩn nặng)",
                            Unit = "bộ",
                            UnitPrice = 150000m
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hotel.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "$2a$11$/LMRtOKzu0S3y3Wy61vsPeGaBR.YvvmkgijRmvbobvp2RNSlrkD3e",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "manager@hotel.com",
                            FullName = "Manager User",
                            IsActive = true,
                            PasswordHash = "$2a$11$T0pLWQ97vlvtz6TZar.kpeCGQeYKu3ojVW/99TcqzI5n3FWPEbPma",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "receptionist@hotel.com",
                            FullName = "Receptionist User",
                            IsActive = true,
                            PasswordHash = "$2a$11$1J39Dq0KNZJB5wIWzBxdAOOZx8hsLsvUFsdlq3f4sCTAMvdJNw7l6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "service@hotel.com",
                            FullName = "Service Staff",
                            IsActive = true,
                            PasswordHash = "$2a$11$A4f9RZSr6u.ePghf680l8eU5FJos.cO0eqaadtofI4wY4pu5D/Gb.",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("BusinessObjects.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("BusinessObjects.Entities.AuditLog", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Entities.GuestAccount", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Guest", "Guest")
                        .WithOne()
                        .HasForeignKey("BusinessObjects.Entities.GuestAccount", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("BusinessObjects.Entities.HousekeepingRequest", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "HandledByUser")
                        .WithMany()
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.Stay", "Stay")
                        .WithMany()
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Invoice", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.Stay", "Stay")
                        .WithOne("Invoice")
                        .HasForeignKey("BusinessObjects.Entities.Invoice", "StayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Payment", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Entities.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("ReceivedByUser");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Reservation", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BusinessObjects.Entities.RolePermission", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Room", b =>
                {
                    b.HasOne("BusinessObjects.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceItem", b =>
                {
                    b.HasOne("BusinessObjects.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("ServiceItems")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceOrder", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.Stay", "Stay")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceOrderDetail", b =>
                {
                    b.HasOne("BusinessObjects.Entities.ServiceItem", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceItem");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Stay", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "CheckedInByUser")
                        .WithMany()
                        .HasForeignKey("CheckedInByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.User", "CheckedOutByUser")
                        .WithMany()
                        .HasForeignKey("CheckedOutByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.Reservation", "Reservation")
                        .WithOne("Stay")
                        .HasForeignKey("BusinessObjects.Entities.Stay", "ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckedInByUser");

                    b.Navigation("CheckedOutByUser");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Surcharge", b =>
                {
                    b.HasOne("BusinessObjects.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusinessObjects.Entities.Stay", "Stay")
                        .WithMany("Surcharges")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Entities.SurchargeItem", "SurchargeItem")
                        .WithMany("Surcharges")
                        .HasForeignKey("SurchargeItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Stay");

                    b.Navigation("SurchargeItem");
                });

            modelBuilder.Entity("BusinessObjects.Entities.User", b =>
                {
                    b.HasOne("BusinessObjects.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Reservation", b =>
                {
                    b.Navigation("Stay");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BusinessObjects.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceCategory", b =>
                {
                    b.Navigation("ServiceItems");
                });

            modelBuilder.Entity("BusinessObjects.Entities.ServiceOrder", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjects.Entities.Stay", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("ServiceOrders");

                    b.Navigation("Surcharges");
                });

            modelBuilder.Entity("BusinessObjects.Entities.SurchargeItem", b =>
                {
                    b.Navigation("Surcharges");
                });
#pragma warning restore 612, 618
        }
    }
}
