using BusinessObjects.Enums;
using Repositories;
using System.Globalization;
using System.Text;
namespace Services;

public sealed class ReportService : IReportService
{
    private readonly IReportRepository _r; public ReportService() : this(new ReportRepository()) { }
    public ReportService(IReportRepository r) => _r = r;
    public async Task<ServiceResult<RevenueReport>> GetRevenueAsync(DateTime from, DateTime to) { if (AppSession.RoleName is not ("Admin" or "Manager")) return ServiceResult<RevenueReport>.Failure("Ban khong co quyen xem bao cao."); from = from.Date; to = to.Date; if (to < from) return ServiceResult<RevenueReport>.Failure("Ngay ket thuc phai bang hoac sau ngay bat dau."); var end = to.AddDays(1); var invoices = await _r.GetInvoicesAsync(from, end); var payments = await _r.GetPaymentsAsync(from, end); var days = invoices.Select(x => x.InvoiceDate.Date).Union(payments.Select(x => x.PaymentDate.Date)).Distinct().OrderByDescending(x => x).Select(d => { var di = invoices.Where(x => x.InvoiceDate.Date == d).ToList(); return new RevenueByDay(d, di.Sum(x => x.RoomCharge), di.Sum(x => x.ServiceCharge), di.Sum(x => x.SurchargeAmount), di.Sum(x => x.DiscountAmount), di.Sum(x => x.TotalAmount), payments.Where(x => x.PaymentDate.Date == d).Sum(x => x.Amount)); }).ToList(); var report = new RevenueReport(from, to, invoices.Sum(x => x.RoomCharge), invoices.Sum(x => x.ServiceCharge), invoices.Sum(x => x.SurchargeAmount), invoices.Sum(x => x.DiscountAmount), invoices.Sum(x => x.TotalAmount), payments.Sum(x => x.Amount), days); return ServiceResult<RevenueReport>.Success(report); }
    public async Task<ServiceResult<string>> ExportRevenueCsvAsync(DateTime from, DateTime to) { var result = await GetRevenueAsync(from, to); if (!result.Ok || result.Data == null) return ServiceResult<string>.Failure(result.Message); var b = new StringBuilder("Date,RoomRevenue,ServiceRevenue,SurchargeRevenue,DiscountAmount,InvoiceRevenue,CollectedAmount\r\n"); foreach (var x in result.Data.ByDay) b.AppendLine(string.Join(',', x.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.RoomRevenue.ToString(CultureInfo.InvariantCulture), x.ServiceRevenue.ToString(CultureInfo.InvariantCulture), x.SurchargeRevenue.ToString(CultureInfo.InvariantCulture), x.DiscountAmount.ToString(CultureInfo.InvariantCulture), x.InvoiceRevenue.ToString(CultureInfo.InvariantCulture), x.CollectedAmount.ToString(CultureInfo.InvariantCulture))); return ServiceResult<string>.Success(b.ToString(), "Da tao noi dung CSV."); }
    public async Task<ServiceResult<OccupancyReport>> GetOccupancyAsync() { if (AppSession.RoleName is not ("Admin" or "Manager")) return ServiceResult<OccupancyReport>.Failure("Ban khong co quyen xem bao cao."); var rooms = await _r.GetRoomsAsync(); var occupied = rooms.Count(x => x.Status == RoomStatus.Occupied); var reserved = rooms.Count(x => x.Status == RoomStatus.Reserved); var rate = rooms.Count == 0 ? 0 : Math.Round((decimal)(occupied + reserved) / rooms.Count * 100, 2); return ServiceResult<OccupancyReport>.Success(new OccupancyReport(rooms.Count, rooms.Count(x => x.Status == RoomStatus.Available), reserved, occupied, rate)); }
}
