using BusinessObjects.Entities; using BusinessObjects.Enums; using Repositories;
namespace Services;
public sealed class ServiceOrderService : IServiceOrderService
{
    private readonly IServiceOrderRepository _orders;private readonly IServiceCatalogRepository _catalog;public ServiceOrderService():this(new ServiceOrderRepository(),new ServiceCatalogRepository()){}public ServiceOrderService(IServiceOrderRepository o,IServiceCatalogRepository c){_orders=o;_catalog=c;}
    public Task<List<ServiceOrder>> GetByStayAsync(int id)=>_orders.GetByStayAsync(id);
    public async Task<ServiceResult<ServiceOrder>> CreateAsync(int stayId,IReadOnlyCollection<ServiceOrderLine> lines)
    { if(lines.Count==0||lines.Any(x=>x.Quantity<=0))return ServiceResult<ServiceOrder>.Failure("Don dich vu khong hop le.");if(!await _orders.IsStayActiveAsync(stayId))return ServiceResult<ServiceOrder>.Failure("Chi phong dang co khach o moi duoc goi dich vu.");var items=await _catalog.GetItemsAsync(true);var map=items.ToDictionary(x=>x.Id);if(lines.Any(x=>!map.ContainsKey(x.ServiceItemId)))return ServiceResult<ServiceOrder>.Failure("Co dich vu khong ton tai hoac da ngung ban.");var x=new ServiceOrder{StayId=stayId,OrderDate=DateTime.Now,Status=ServiceOrderStatus.Pending,CreatedByUserId=AppSession.CurrentUser?.Id};foreach(var line in lines){var item=map[line.ServiceItemId];x.OrderDetails.Add(new ServiceOrderDetail{ServiceItemId=item.Id,Quantity=line.Quantity,UnitPrice=item.UnitPrice,Subtotal=item.UnitPrice*line.Quantity});}x.TotalAmount=x.OrderDetails.Sum(d=>d.Subtotal);await _orders.AddAsync(x);return ServiceResult<ServiceOrder>.Success(x,"Da tao don dich vu."); }
    public async Task<ServiceResult<ServiceOrder>> ChangeStatusAsync(int id,ServiceOrderStatus status){if(!Enum.IsDefined(status))return ServiceResult<ServiceOrder>.Failure("Trang thai khong hop le.");var x=await _orders.ChangeStatusAsync(id,status);return x==null?ServiceResult<ServiceOrder>.Failure("Khong tim thay don dich vu."):ServiceResult<ServiceOrder>.Success(x,"Da cap nhat trang thai.");}
}
